import { Router } from 'express';
import { z } from 'zod';
import { adminController } from '../controllers/admin.controller.js';
import { requireRole } from '../middleware/requireRole.js';
import { validate } from '../middleware/validate.js';
import { auditLogger } from '../middleware/auditLogger.js';
import { id, paginationQuery } from '../schemas/index.js';
const router = Router();
router.use(requireRole('SUPER_ADMIN'));
router.get('/users', validate({ query: paginationQuery }), adminController.users);
router.patch('/users/:id/activate', validate({ params: z.object({ id }) }), auditLogger('admin.user.activate'), adminController.activate);
router.patch('/users/:id/deactivate', validate({ params: z.object({ id }) }), auditLogger('admin.user.deactivate'), adminController.deactivate);
router.patch('/users/:id/role', validate({ params: z.object({ id }), body: z.object({ role: z.enum(['SUPER_ADMIN', 'ADMIN', 'MEMBER']) }) }), auditLogger('admin.user.role'), adminController.role);
router.get('/audit-log', validate({ query: paginationQuery }), adminController.audit);
router.get('/stats', adminController.stats);
export default router;
