import { Router } from 'express';
import authRoutes from './auth.routes.js';
import usersRoutes from './users.routes.js';
import organizationsRoutes from './organizations.routes.js';
import projectsRoutes from './projects.routes.js';
import issueTypesRoutes from './issueTypes.routes.js';
import customFieldsRoutes from './customFields.routes.js';
import issuesRoutes from './issues.routes.js';
import workflowsRoutes from './workflows.routes.js';
import commentsRoutes from './comments.routes.js';
import attachmentsRoutes from './attachments.routes.js';
import sprintsRoutes from './sprints.routes.js';
import backlogsRoutes from './backlogs.routes.js';
import worklogsRoutes from './worklogs.routes.js';
import timersRoutes from './timers.routes.js';
import performanceRoutes from './performance.routes.js';
import searchRoutes from './search.routes.js';
import notificationsRoutes from './notifications.routes.js';
import webhooksRoutes from './webhooks.routes.js';
import adminRoutes from './admin.routes.js';
import spacesRoutes from './spaces.routes.js';
import pagesRoutes from './pages.routes.js';
import analyticsRoutes from './analytics.routes.js';
import { authRequired } from '../middleware/auth.js';
import { pagesController } from '../controllers/pages.controller.js';

const router = Router();
router.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok', at: new Date().toISOString() } }));
router.use('/auth', authRoutes);
router.get('/spaces/shared/:token', pagesController.shared);
router.use(authRequired);
router.use('/users', usersRoutes);
router.use('/org', organizationsRoutes);
router.use('/projects', projectsRoutes);
router.use('/projects/:id/issue-types', issueTypesRoutes);
router.use('/projects/:id/custom-fields', customFieldsRoutes);
router.use('/projects/:projectId/issues', issuesRoutes);
router.use('/projects/:projectId/workflows', workflowsRoutes);
router.use('/projects/:projectId/sprints', sprintsRoutes);
router.use('/projects/:projectId/backlog', backlogsRoutes);
router.use('/projects/:projectId/webhooks', webhooksRoutes);
router.use('/issues/:issueId/comments', commentsRoutes);
router.use('/issues/:issueId/attachments', attachmentsRoutes);
router.use('/issues/:issueId/worklogs', worklogsRoutes);
router.use('/timers', timersRoutes);
router.use('/performance', performanceRoutes);
router.use('/search', searchRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/admin', adminRoutes);
router.use('/spaces', spacesRoutes);
router.use('/spaces/:spaceId/pages', pagesRoutes);
router.use('/spaces/:spaceId/analytics', analyticsRoutes);
export default router;
