import { Router } from 'express';
import { z } from 'zod';
import { searchController } from '../controllers/search.controller.js';
import { validate } from '../middleware/validate.js';
import { auditLogger } from '../middleware/auditLogger.js';
import { id, searchSchemas } from '../schemas/index.js';
const router = Router();
router.get('/', searchController.global);
router.get('/issues', searchController.issues);
router.post('/reindex', auditLogger('search.reindex'), searchController.reindex);
router.post('/filters/save', validate({ body: searchSchemas.saveFilter }), auditLogger('filter.save'), searchController.saveFilter);
router.get('/filters', searchController.filters);
router.delete('/filters/:id', validate({ params: z.object({ id }) }), auditLogger('filter.delete'), searchController.deleteFilter);
export default router;
