import { Router } from 'express';
import { z } from 'zod';
import { workflowsController } from '../controllers/workflows.controller.js';
import { validate } from '../middleware/validate.js';
import { auditLogger } from '../middleware/auditLogger.js';
import { id, workflowSchemas } from '../schemas/index.js';
const router = Router({ mergeParams: true });
router.get('/', workflowsController.list);
router.post('/', validate({ body: workflowSchemas.workflow }), auditLogger('workflow.create'), workflowsController.create);
router.get('/:wfId', validate({ params: z.object({ projectId: id, wfId: id }) }), workflowsController.get);
router.patch('/:wfId', validate({ params: z.object({ projectId: id, wfId: id }), body: workflowSchemas.workflow.partial() }), auditLogger('workflow.update'), workflowsController.update);
router.delete('/:wfId', validate({ params: z.object({ projectId: id, wfId: id }) }), auditLogger('workflow.delete'), workflowsController.remove);
router.post('/:wfId/statuses', validate({ params: z.object({ projectId: id, wfId: id }), body: workflowSchemas.status }), auditLogger('workflow.status.create'), workflowsController.createStatus);
router.patch('/:wfId/statuses/:sId', validate({ params: z.object({ projectId: id, wfId: id, sId: id }), body: workflowSchemas.status.partial() }), auditLogger('workflow.status.update'), workflowsController.updateStatus);
router.delete('/:wfId/statuses/:sId', validate({ params: z.object({ projectId: id, wfId: id, sId: id }) }), auditLogger('workflow.status.delete'), workflowsController.removeStatus);
router.post('/:wfId/transitions', validate({ params: z.object({ projectId: id, wfId: id }), body: workflowSchemas.transition }), auditLogger('workflow.transition.create'), workflowsController.createTransition);
router.patch('/:wfId/transitions/:tId', validate({ params: z.object({ projectId: id, wfId: id, tId: id }), body: workflowSchemas.transition.partial() }), auditLogger('workflow.transition.update'), workflowsController.updateTransition);
router.delete('/:wfId/transitions/:tId', validate({ params: z.object({ projectId: id, wfId: id, tId: id }) }), auditLogger('workflow.transition.delete'), workflowsController.removeTransition);
router.post('/:wfId/transitions/:tId/guards', validate({ params: z.object({ projectId: id, wfId: id, tId: id }), body: workflowSchemas.guard }), auditLogger('workflow.guard.create'), workflowsController.createGuard);
router.delete('/:wfId/transitions/:tId/guards/:gId', validate({ params: z.object({ projectId: id, wfId: id, tId: id, gId: id }) }), auditLogger('workflow.guard.delete'), workflowsController.removeGuard);
export default router;
