import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Square, X } from 'lucide-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Feedback, FieldError } from '@/components/common/Feedback';
import { LoadingButton } from '@/components/common/LoadingButton';
import { issuesApi } from '@/api/issues.api';
import { queryKeys } from '@/api/queryKeys';
import { getApiErrorMessage } from '@/lib/api-error';
import type { Issue } from '@/types';
type Notice = { tone: 'success' | 'error' | 'info' | 'warning'; title: string; message?: string } | null;
export function SubTaskList({ projectId, parentIssue }: { projectId: string; parentIssue: Issue }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [titleError, setTitleError] = useState(''); const [notice, setNotice] = useState<Notice>(null); const qc = useQueryClient(); const subtasks = parentIssue.children ?? []; const create = useMutation({ mutationFn: () => issuesApi.create(projectId, { title: title.trim(), description: '', parentId: parentIssue.id, issueTypeId: parentIssue.issueType?.id, workflowStatusId: parentIssue.workflowStatus?.id, priority: parentIssue.priority }), onSuccess: (issue) => { setTitle(''); setTitleError(''); setOpen(false); setNotice({ tone: 'success', title: 'Sub-task created', message: `${issue.key} was added under ${parentIssue.key}.` }); qc.invalidateQueries({ queryKey: queryKeys.issue(parentIssue.id) }); qc.invalidateQueries({ queryKey: ['issues', projectId] }); }, onError: (error) => setNotice({ tone: 'error', title: 'Could not create sub-task', message: getApiErrorMessage(error) }) }); function submit() { if (!title.trim()) { setTitleError('Sub-task title is required.'); return; } setTitleError(''); setNotice(null); create.mutate(); } return <div className="space-y-3 rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Sub-tasks <span className="text-xs text-muted-foreground">({subtasks.length})</span></h3><Button size="sm" variant="outline" onClick={() => setOpen((v) => !v)}>{open ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />} {open ? 'Cancel' : 'Add'}</Button></div><Feedback tone={notice?.tone} title={notice?.title} message={notice?.message} />{open && <div className="space-y-2"><div className="flex gap-2"><Input value={title} onChange={(e) => { setTitle(e.target.value); if (titleError) setTitleError(''); }} placeholder="Sub-task title" onKeyDown={(e) => { if (e.key === 'Enter') submit(); }} /><LoadingButton loading={create.isPending} loadingText="Adding…" onClick={submit}>Create</LoadingButton></div><FieldError message={titleError} /></div>}<div className="space-y-2">{subtasks.map((task) => <Link key={task.id} to={`/projects/${projectId}/issues/${task.id}`} className="flex items-center justify-between gap-2 rounded-md border p-2 text-sm hover:bg-accent"><span className="flex items-center gap-2"><Square className="h-4 w-4" /> <span className="font-mono text-xs text-muted-foreground">{task.key}</span> {task.title}</span><span className="rounded-full border px-2 py-0.5 text-xs">{task.workflowStatus?.name}</span></Link>)}{!subtasks.length && <p className="text-sm text-muted-foreground">No sub-tasks yet. Break this issue into smaller work items.</p>}</div></div>; }
